version: '3.4'
 

services:
  gringottsbank.service:
    container_name: gringottsbank.service
    image: ${DOCKER_REGISTRY-}gringottsbankservice
    build:
      context: .
      dockerfile: GringottsBank.Service/Dockerfile
    environment:
        ConnectionStrings: 
            GringottsBankDB=Data Source=sqlserver;Initial Catalog=GringottsBankDB;User ID=arka_sa;Password=Your_password123
            TestDB=TestDB
    depends_on: 
        - sqlserver

  sqlserver:
    container_name: sqlserver
    image: ${DOCKER_REGISTRY-}gringottsbanksqlserver
    build:
      context: .
      dockerfile: Database/Dockerfile
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: 2astazeY
        MSSQL_DB: GringottsBankDB
        MSSQL_USER: arka_sa
        MSSQL_PASSWORD: Your_password123
    ports:
        - 1433:1433 
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$SA_PASSWORD -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s     
    
