datasources:
- name: Loki_GringottsBank
  access: proxy
  type: loki
  url: http://loki:3100
  isDefault: true

- name: Prometheus
  access: proxy
  type: prometheus
  url: http://prometheus:9090
  isDefault: true
