{
 "title": "Gringotts Bank API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests Received",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_received_total{}" }
   ]
  },
  {
   "title": "No Of Threads",
   "type": "timeseries",
   "description": "No Of Threads",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_num_threads{}" }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total{}" }
   ]
  },
  {
   "title": "Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_virtual_memory_bytes{}" }
   ]
  },
  {
   "title": "Application UP",
   "type": "timeseries",
   "description": "Application UP check",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "up{}" }
   ]
  }
 ]
}